- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/config/ur5_controllers.yaml
- ur_robot_driver/hardware_interface_plugin.xml
- ur_robot_driver/include/ur_robot_driver/dashboard_client_ros.h
- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/include/ur_robot_driver/robot_state_helper.h
- ur_robot_driver/launch/ur5_bringup.launch.py
- ur_robot_driver/package.xml
- ur_robot_driver/src/dashboard_client_ros.cpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/src/robot_state_helper.cpp
- ur_robot_driver/src/robot_state_helper_node.cpp
This sets up the framework for the hardware_interface.
- Inherits from `hardware_interface::components::SystemInterface`
- Changes namespaces in the ur_robot_driver package to match the package name (IIRC this is a ROS convention)
- The launch file (ur5_bringup.launch.py) does not work yet due to this ros2_control issue: https://github.com/ros-controls/ros2_control/issues/229
I'm not sure if anybody is available to review this yet. Maybe @gavanderhoorn? If not, I'll let it simmer a day or so before merging to `develop`
> Hardware interface framework

- ur_ros2_control_demos/config/ur_ros2_control.yaml
> Fix joint_trajectory_controller execution - set stopped_velocity_tolerance to zero

- ur_robot_driver/include/ur_robot_driver/dashboard_client_ros.h
- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/src/dashboard_client_ros.cpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_ros2_control_demos/launch/ur5_e_system_position_only.launch.py
Addresses #26 
Changes
* Fixed issue during capsuled trigger service creation
* Fixed issue when connecting mutliple times
* Added try catch blocks since it is no longer done during the service call in ROS2
* Start dashboard client from within hardware interface
* Made use of dashboard client namespace for service calls
> Dashboard client fixes

- ur_controllers/src/force_torque_sensor_controller.cpp
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_controllers/src/speed_scaling_state_controller.cpp
`controller_interface::return_type::SUCCESS` is deprecated
> Clean up ros2_control "return type" warning

- README.md
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
* Before sending data to the robot the hardware interface not verifies if the controller has send new data or if the current joint values are just stale output.
* Fixed a timing issue in the scaled trajectory controller. When executing multiple trajectories subsequently, the scaled timing was not handled correctly which caused a delay of the starting point of the trajectory.
* Removed **Attention** Flags related to move to home bug in the Readme file
> Fix move to home bug

- ur_controllers/package.xml
- ur_robot_driver/package.xml
This might break the ci pipeline but otherwise the driver is not build-able for new users which is in my opinion worse than a broken ci
> Reintegrating missing ur_client_library dependency since the break the building process

- ur_robot_driver/src/hardware_interface.cpp
Fixes #111 
As @urmahp already figured out the async check had to be done outside of the check whether the program is running at the moment
> Moved Async check out of script running check

- Universal_Robots_ROS2_Driver.repos
fixes #114 
change version of ros2_controllers in Universal_Robots_ROS2_Driver.repos to 0.2.1 - project builds now
> change version of ros2_controllers in Universal_Robots_ROS2_Driver.repos to 0.2.1 - project builds now

- .github/workflows/issue-states.yml
See https://github.com/dessant/issue-states
I tested this on a separate repo for the following conditions:
- Closing an Issue will still result in it being moved to the Done column in any automated Project boards it is associated with.
- **New**: Moving an Issue to the Done column in any Project board will result in the Issue being closed. This can then trigger the Issue being moved to the Done column in other Project boards if they are automated.
- Reopening a closed Issue will still result in it being moved to the In progress column in any automated Project boards it is associated with.
- **New**: Moving an issue from the Done column to any other column will reopen the Issue. This can then trigger the Issue being moved to the In progress column in any automated Project boards (including …
> Use dessant/issue-states workflow to close issues moved to project board Done column

- Universal_Robots_ROS2_Driver.repos
- ur_bringup/config/test_goal_publishers_config.yaml
- ur_description/urdf/ur.ros2_control.xacro
This PR comes in combination with [ros2_controlPR128](https://github.com/ros-controls/ros2_control_demos/pull/128).
The idea is to disable execution of test scripts if the start state check has not satisfied configured limits.
> Add parameters for checking start state

- ur_controllers/src/force_torque_sensor_broadcaster.cpp
- ur_controllers/src/speed_scaling_state_broadcaster.cpp
PR info:
- adapts `ur_controllers` package which components inherit from [`ControllerInterface`](https://github.com/ros-controls/ros2_control/blob/master/controller_interface/include/controller_interface/controller_interface.hpp)
- follows changes in [ros2_control](https://github.com/ros-controls/ros2_control/pull/504/files) and [ros2_controllers](https://github.com/ros-controls/ros2_controllers/pull/224)
> Modifiy parameter declaration - approach equalization with ros-controls dependencies

- README.md
the `--state` flag became obsolete and `--set-state` should be used.
> Correct obsolete ros2controlcli flags

- ur_description/urdf/ur_macro.xacro
Minor change to avoid the need to creat a "prefix" xacro:arg in calling xacros
> Fixes access to the "prefix" property

- ur_controllers/include/ur_controllers/force_torque_sensor_broadcaster.hpp
- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.hpp
- ur_controllers/include/ur_controllers/speed_scaling_state_broadcaster.hpp
- ur_controllers/src/force_torque_sensor_broadcaster.cpp
- ur_controllers/src/gpio_controller.cpp
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_controllers/src/speed_scaling_state_broadcaster.cpp
This PR is related/depends on merge on ros-controls/ros2_control#520 (and ros2_control/ros2_controllers#241)﻿
> Update controllers adding dt in to update as in ros2_control

- README.md
I got an opportunity to use a UR hardware robot for the first time in ROS2  :+1:   These are some README improvements that would have helped me figure it out faster, I think.
- Add a Network Settings section with a good default setup.
- The URCap program is not located in the Resources folder, so delete that bit.
- Describe how to modify Host IP of the external_control URCap.
- Prompt the user to launch the URCap after the appropriate launch files. It's very easy to forget.
Fixes #182
> README readability improvements

- ur_bringup/launch/ur_control.launch.py
If I understand right, `robot_controller` is the joint controller that is launched by default. I think that's a little confusing because there are several controllers running on the robot. Would prefer to name it `initial_joint_controller` to specify exactly what it does.
Currently, the options in ur_controllers.yaml are `joint_trajectory_controller` and `forward_velocity_controller`
> Rename the joint controller that is started by default

- ur_robot_driver/src/hardware_interface.cpp
PR solves the problem of reporting the controller status active while its belonging command interface is disabled in the system.
Closes #190
> Fix prepare and perform switch operation

- ur_robot_driver/src/hardware_interface.cpp
In the current implementation of the ros-controls/ros2_control [System](https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/src/system.cpp#L222) the [read](https://github.com/ros-controls/ros2_control/blob/c4cdbee6c9139f9e85c9d03d62d05ca683cc83a8/hardware_interface/src/system.cpp#L215-L229) and [write](https://github.com/ros-controls/ros2_control/blob/c4cdbee6c9139f9e85c9d03d62d05ca683cc83a8/hardware_interface/src/system.cpp#L231-L245) are not called if their lifecycle state is different than `PRIMARY_STATE_INACTIVE` or `PRIMARY_STATE_ACTIVE`. This is changed when the `SystemInterface` returns [`hardware_interface::return_type::ERROR`](https://github.com/ros-controls/ros2_control/blob/c4cdbee6c9139f9e85c9d03d62d05ca683cc83a8/hardware_interface/src/system.cpp#L241). …
> Make reading and writing work when hardware is disconnected

- ur_bringup/launch/ur_control.launch.py
https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/commit/3e099dda8c42e3f584cb10839d3a02aec2cc3f49 seems to have a simple copy paste error, where the executable argument went missing.
This should fix https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/247
> fix missing executable arg of joint_state_broadcaster

- ur_robot_driver/src/hardware_interface.cpp
If writing to the hardware is not possible, as the interpreting program
is currently not running, there's no need to print an error message in each
control cycle.
This aims at fixing #262 and possibly #264
> Do not print an error output if writing is not possible

- ur_bringup/config/ur10_update_rate.yaml
- ur_bringup/config/ur10e_update_rate.yaml
- ur_bringup/config/ur16e_update_rate.yaml
- ur_bringup/config/ur3_update_rate.yaml
- ur_bringup/config/ur3e_update_rate.yaml
- ur_bringup/config/ur5_update_rate.yaml
- ur_bringup/config/ur5e_update_rate.yaml
- ur_bringup/launch/ur_control.launch.py
- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/package.xml
- ur_robot_driver/src/ur_ros2_control_node.cpp
PR info:
Adds separate ros2 control node without sleeping in the main loop as a way to solve the [`Pipeline produced overflow!` problem](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/210).
Instead of #263.
> Separate control node

- ur_robot_driver/src/hardware_interface.cpp
This is now fully functional, and it should be tested on hardware with  UniversalRobots/Universal_Robots_ROS2_Description#16.
> Use gpio tag in urdf

- ur_moveit_config/config/controllers.yaml
I forgot to add this in #287.
Nevertheless, when I change this an `underlow` exception in controller happens, which crashes ros2_control_node
```
﻿[ros2_control_node-1] terminate called after throwing an instance of 'std::underflow_error'
[ros2_control_node-1]   what():  addition leads to int64_t underflow
```
@fmauch do you have any idea why this should happen when MoveIt is used with scaling JTC? (I assume you experienced this issue already.)
Until this is fixed/merged users would have to set "joint_trajectory_controller" as default when using the driver with MoveIt.
> Change default controller in MoveIt config

- README.md
- Universal_Robots_ROS2_Driver-not-released.foxy.repos
- Universal_Robots_ROS2_Driver-not-released.galactic.repos
As risen for example in #296 our current installation instructions build a lot from source using the default branches. Obviously, this introduces changes not really applicable to older ROS versions.
For example, ros2_control dropped support for the deprecated `spawner.py` on the main branch. Therefore, I suggest changing the README to use the distro-specific dependency definitions and I updated the galactic definitions here.
In the long run we should try to reduce those as well, as packages from our `not-released...` rosdistro files are indeed released. But that's for another PR...
> Update readme install instructions

- ur_bringup/launch/ur_control.launch.py
- ur_robot_driver/scripts/tool_communication.py
As discussed in #256 it would be nice to actually start the tool communication if the flag `use_tool_communication` is set.
A quick side note: I decided against adding this to all launch files, as the `use_tool_communication` argument also only exists inside the `ur_control.launch` file.
I'll mark this ready once I've actually tested on real hardware.
> Start the tool communication script if the flag is set

- ur_moveit_config/config/kinematics.yaml
- ur_moveit_config/launch/ur_moveit.launch.py
This fixes #307 which outlines a regression introduced in #278
~~@destogl As we use the raw string "ur_moveit_config" in several other places, it probably doesn't harm to leave this.~~
With the implementation from bf37c75 it should be possible to keep both.
> Load kinematics parameters as yaml

- .github/workflows/foxy-semi-binary-build.yml
This got lost in #312. Apparently, workflows with a syntax error do not show up as failed in the PR.
> [Foxy] Fix a syntax error in semi-binary build

- .pre-commit-config.yaml
From some reason, the old version is failing import requirements recently. Bumping the version fixes the issue.
> Fix erroneous version of python black in pre-commit

- Universal_Robots_ROS2_Driver-not-released.foxy.repos
- Universal_Robots_ROS2_Driver.repos
The ROS2 changes have been merged upstream.
This is basically a backport of #336
> Fix ur msgs url

- ur_bringup/launch/ur_control.launch.py
It only makes sense to start the controller_stopper when real hardware (or URSim) is used.
> Only start controller_stopper when not using fake_hardware

- .github/workflows/ci-ros-lint.yml
This splipped through in #340 and fixes the ament_copyright check.
In my opinion, this is not a file that can be copyrighted, hence I suggest ignoring it.
> ignore doc/conf.py from copyright checks

- .github/workflows/galactic-binary-build.yml
- .github/workflows/galactic-semi-binary-build.yml
- .github/workflows/galactic-source-build.yml
- README.md
We've branched out for ROS2 galactic now, so let's update the README and CI accordingly.
Once this is merged, we can start merging in the `humble+`-labeled MRs (#351, #345, #339)
> Update README and workflows as galactic is now branched out

- .github/workflows/foxy-source-build.yml
Since the scheduled build has to be run from the main branch,
but we need to use the repos file from the foxy branch, we have to specify
it directly.
> Fix repos file for scheduled foxy source build

- .github/workflows/foxy-binary-build.yml
- README.md
- Universal_Robots_ROS2_Driver-not-released.foxy.repos
- ur_bringup/launch/test_joint_trajectory_controller.launch.py
- ur_bringup/launch/test_scaled_joint_trajectory_controller.launch.py
- ur_bringup/package.xml
Closing #342 
Also affects #347, as the dependency is not put in. Unfortunately, this will lead to an error when launching the package if it is not built inside the workspace.
> Foxy: Update dependencies and binary repos file

- .github/workflows/galactic-binary-build.yml
- .github/workflows/galactic-semi-binary-build.yml
As scheduled runs have to run on the main branch, we have to explicitly
checkout the distro's branch in the CI run.
> Force galactic branch for scheduled builds

- .github/workflows/foxy-binary-build.yml
since scheduled builds run on the default branch, this has to be adapted.
The file got removed on the foxy branch which is checked out by this job.
This got updated in #373
> Remove Foxy upstream not-released file

- ur_robot_driver/config/ur_controllers.yaml
This got lost in #403 since it was started before #405 was merged.
> Fixed controller name for force_torque_sensor_broadcaster

- ur_moveit_config/CMakeLists.txt
Similar to fd66700db47aefe7fa8f64e4068d9d5213d367d5 we need to remove that dependency on the main branch.
> Remove non-required dependency from CMakeLists

- .github/workflows/humble-execution-test.yml
- .github/workflows/rolling-execution-test.yml
- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- Universal_Robots_ROS2_Driver.humble.repos
- Universal_Robots_ROS2_Driver.rolling.repos
ros-controls/ros2_controllers#360 already fixed a bug related to parameter handling in forward controllers. Until next sync we have to use the source repo for error-free controller startup.
> Use ros2_controllers sources

- ur_robot_driver/src/dashboard_client_ros.cpp
Since setting the receive timeout takes the time_buffer as an argument
this raises a "may be used uninitialized" warning. Setting this to 0
explicitly should prevent that.
> Silence a compilation warning

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
See https://github.com/ros-controls/ros2_controllers/pull/374
Note: This implementation will enforce spline based interpolation and therefore omit the JTC's new feature of specifying the interpolation method.
> Adapted to JTC interpolation method feature

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/src/controller_stopper.cpp
There have been upstream changes regarding stopped controllers and querying the interface name inside controllers.
> Adapt ros control api

- ur_robot_driver/package.xml
Currently, our binary package builds for the driver [fail](https://build.ros2.org/job/Fbin_uF64__ur_robot_driver__ubuntu_focal_amd64__binary/) because of the missing declaration.
This PR should fix that.
> added ur_bringup to test_depend of ur_robot_driver

- ur_moveit_config/launch/ur_moveit.launch.py
Workaround for #390 (simulated hardware throws an underflow error which breaks scaled_joint_trajectory_controller #301) by allowing user to specify whether the robot driver is using fake_hardware as CLI argument. If this is the case, MoveIt will fall back on the joint_trajectory_controller. This behavior is disabled by default and requires user to manually set argument is_using_fake_hardware to true when running ur_moveit.launch.py.
> add ur_moveit.launch.py parameter to use working controller when using fake hardware

- README.md
- ur_calibration/CMakeLists.txt
- ur_calibration/README.md
- ur_calibration/include/ur_calibration/calibration.hpp
- ur_calibration/include/ur_calibration/calibration_consumer.hpp
- ur_calibration/launch/calibration_correction.launch.py
- ur_calibration/package.xml
- ur_calibration/src/calibration.cpp
- ur_calibration/src/calibration_consumer.cpp
- ur_calibration/src/calibration_correction.cpp
- ur_calibration/test/calibration_test.cpp
> Add ur_calibration package

- ur_moveit_config/launch/ur_moveit.launch.py
This was falsely introduced earlier. This is a working version. The wrong version was introduced in #464, where I seemed to miss checking real hardware. Thanks @grassjelly for providing this solution in https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/470#issuecomment-1254658620.
> Fix selecting the right controller given fake_hw

- ur_calibration/README.md
The filename with the dual type ending was wrong.
Thanks to @urmahp for finding this inside #451
> Fixes launchfile references

- Universal_Robots_ROS2_Driver.humble.repos
- Universal_Robots_ROS2_Driver.rolling.repos
With the new admittance_controller this is necessary, since we have ros2_control and ros2_controllers already in the repos file.
Adding the admittance_controller to the driver would be another step (see #511). This PR just keeps our CI stable.
> add kinematics_interface and control_msgs to semi-src workspace

- ur_moveit_config/launch/ur_moveit.launch.py
The patch in #464 fixes my problem where the UR Gazebo Sim won't move because the Scaled JTC controller is loaded into the MoveitSimpleControllerManager as default controller (and there is no way to change it during runtime through e.g. a service). Building main branch breaks because of same error message as in #434, so I found it simpler to backport a single commit from main.
This is my very first pull request in a professional repository so sorry in advance for any mistakes or shortages. For example, I am not sure which tests you refer to under item 3 in the [contributing page](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/f580ae73edc67b10ce89ff72d30f70269935e39d/CONTRIBUTING.md): Are you referring to the pre-commit tests?
> back-port use_fake_hardware parameter in ur_moveit.launch.py to Galactic (#464)

- ur_robot_driver/package.xml
This is needed for the tool forwarding.
> Added dependency to socat

- ur_robot_driver/src/controller_stopper.cpp
Use `activate_controllers` instead of `start_controllers`.
> ur_robot_driver: Controller_stopper fix deprecation warning

- Universal_Robots_ROS2_Driver.humble.repos
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
Since the humble release is currently broken (see #522), this suggests reverting back to the ros2_controllers 2.12.0 API.
Since we wanted to branch out for Humble at some point, anyway, this seems to be a good time to do that.
> Quickfix humble release

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver.humble.repos
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
We reverted to 2.12 compatibility due to the next sync (see #522). Since we have a release with that our humble branch should be made compatible with the new released version. Since the API changed to ros2_controllers 2.13 and dependencies got fixed in 2.14 we build 2.14 from the upstream source space as long as 2.14 hasn't landed in main, yet.
I guess squashing both commits into one would make sense, as they won't produce functioning builds without each other.
> Ros2 controllers 2.14

- README.md
This seems to have been forgotten when branching out humble.
> Document cloning the correct branch for humble

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver.humble.repos
ros2_controllers forked out for humble. This PR adapts our pipeline accordingly. I've also increased the source version of ros2_controllers in the binary build, since this is not yet synchronized to the main repo.
> Humble semi binary ros2 controllers

- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/src/gpio_controller.cpp
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/src/hardware_interface.cpp
Added launch arguments for reverse ip and script command interface port.
This requires the changes from [pr](https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/111) in the client library and also the changes from [pr](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/38) in the ur ros2 description. 
To be able to use the script commands when the robot is in local control we have to use the urscript from the client, this is being addressed in #316.  
This will fix the issues #420 and #447.
> Added services to set tool voltage and zero force torque sensor

- ur_robot_driver/CMakeLists.txt
The buildfarm currently fails due to an include error on `controller_manager` (see [here](https://build.ros2.org/job/Rbin_ujv8_uJv8__ur_robot_driver__ubuntu_jammy_arm64__binary/89/console)) and i suspect this will fix that.
> Fix cmake dependency on controller_manager

- .github/workflows/humble-source-build.yml
We also run rolling in scheduled builds, so this is more consistent. I find this to be useful, as source builds especially can show errors from different packages and our ci doesn't reflect fixes to those until we push something new to the corresponding branch.
> Perform scheduled runs of the humble source build

- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- Universal_Robots_ROS2_Driver.rolling.repos
This is pretty late to do this, but [moveit_servo was removed from rolling](https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2023-01-06/29094). Hopefully it will be back in with the next sync, but until then this should help.
> moveit_servo is currently not available on rolling

- Universal_Robots_ROS2_Driver-not-released.rolling.repos
Both are released and functional as of the latest sync. Should fix #620.
> Use released versions of moveit2 and ros2_controllers

- Universal_Robots_ROS2_Driver.humble.repos
Only directly using ros2_controllers in semi-binary builds is prone to breakage
> Add ros2_control as direct dependency

- ur_robot_driver/test/robot_driver.py
This should hopefully fix our flaky tests.
Basically the scenario causing problems was that after startup the program running on the robot was in a `paused` state.  This was causing the scaled JTC to not progress forever leading the test into a timeout.
This PR re-arranges the robot-startup in the test file such that the program should always be running.
Basically, the program is started in each test's `setUp()` method after the robot has been put into `RUNNING` mode which is checked.
I have this running [on my fork](https://github.com/fmauch/Universal_Robots_ROS2_Driver/actions/workflows/rolling-binary-build.yml?query=branch%3Adebug_tests) for quite some runs now (since run 111) and this seems to be working fine.
> Fix flaky tests

- ur_moveit_config/config/joint_limits.yaml
- ur_moveit_config/launch/ur_moveit.launch.py
This defines default values for maximum joint accelerations, as MoveIt is otherwise not able to perform time parametrization. The 5rad/s² are from the discussion in https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/issues/46.
This patch only passes these limits to MoveIt. While we could also add them in `ur_description`, this seems incorrect. The robot does not inherently have any limits on joint accelerations (only on torques), and other software using `ur_description` might be able to handle this differently.
> Define default maximum accelerations for MoveIt

- ur_robot_driver/test/robot_driver.py
This came up in the backport of CI fixes https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/647 and seemed to be unrelated to those changes.
> Wait longer for controllers to load and activate

- README.md
The README has been updated on the main branch, also with respect to the binary installation.
This commit ties them together, pointing to humble-specific endpoints,
where necessary.
> Update the toplevel README for humble

- ur_controllers/src/speed_scaling_state_broadcaster.cpp
This should make our buildfarm builds stable again. See [this run](https://build.ros2.org/job/Rdev__ur_robot_driver__ubuntu_jammy_amd64/48/) for instance showing the warning.
Additionally, I'd like to raise the question, whether we should activate `-Wall` for this repo. I think it makes sense in order to track these kind of warnings early in the process.
> Switched out a deprecated header to avoid buildfarm warnings.

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- ur_robot_driver/src/hardware_interface.cpp
Since https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/66 is merged, we'll have to revert the workaround in the driver as well.
> Use tf prefix properly

- ur_calibration/launch/calibration_correction.launch.py
- ur_controllers/CHANGELOG.rst
- ur_moveit_config/launch/ur_moveit.launch.py
- ur_moveit_config/ur_moveit_config/launch_common.py
- ur_robot_driver/CHANGELOG.rst
- ur_robot_driver/launch/test_forward_velocity_controller.launch.py
- ur_robot_driver/launch/test_joint_trajectory_controller.launch.py
- ur_robot_driver/launch/test_scaled_joint_trajectory_controller.launch.py
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/test/dashboard_client.py
- ur_robot_driver/test/robot_driver.py
Black and codespell seem to  be more picky by now, this PR fixes empty lines below function definitions in python files and a typo in our changelogs.
This came up in #640
> Fixed formatting

- .github/workflows/update-ci.yml
Resolves: #678 
Changes:
- Forcing committer and author in automatic create PR workflow
- Using `github-actions[bot] <github-actions[bot]@users.noreply.github.com>` in committer + author fields
This was tested on my forked repo as shown below:
- PR: https://github.com/tungbq/Universal_Robots_ROS2_Driver/pull/1
- Log: https://github.com/tungbq/Universal_Robots_ROS2_Driver/actions/runs/5065138063/jobs/9093387898
> Forcing committer and author in automatic create PR workflow

- README.md
Small fixes to the README based on the recently merged humble README changes. With this, there should be no more relevant differences between humble and rolling apart from different URLs.
> Readme small fixes

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- Universal_Robots_ROS2_Driver.humble.repos
- Universal_Robots_ROS2_Driver.rolling.repos
The idea behind this is basically this:
* If we require direct upstream dependencies in a more recent version, we have the semi-binary builds. With this, it would be acceptable, that the binary builds turn failed if there has been an upstream breaking change, that we already adapted to.
* For development the semi-binary builds are the actually interesting ones. They will keep building upstream dependencies from their most recent versions.
* The binary builds should give us feedback whether the driver will work with the currently released packages. This is only a valid feedback if it is actually built against the released state.
This way, situations like it just happened that our humble release was failing should pop up in the binary-testing earlier in the process, so that we can react on …
> Use binary released packages for binary builds only.

- .github/workflows/iron-binary-main.yml
- .github/workflows/iron-binary-testing.yml
- .github/workflows/iron-semi-binary-main.yml
- .github/workflows/iron-semi-binary-testing.yml
- README.md
- Universal_Robots_ROS2_Driver-not-released.iron.repos
- Universal_Robots_ROS2_Driver.iron.repos
- ci_status.md
This should improve the user's perspective on the actual build status. Together with #708 this will allow us having visible failing pipelines, without giving the impression that the overall package is broken, while there are successful binary builds.
> Split build status into two views & add iron workflows

- ur_robot_driver/src/ur_ros2_control_node.cpp
[Previous investigations](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/60f08359f6484d1671e12bab6e01fc49eb0fadc8/ur_robot_driver/doc/real_time_benchmarking.md) showed that using FIFO scheduling helps keeping cycle times also non non-RT kernels. This combined with non-blocking read can result in a very stable system.
This is, in fact, very close to what the actual controller_manager_node does except that we always use FIFO scheduling independent of the actual kernel in use.
> Use SCHED_FIFO for controller_manager's main thread

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/doc/usage.rst
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/src/urscript_interface.cpp
- ur_robot_driver/test/urscript_interface.py
This PR adds a bare URScript interface using the `ur_client_library`. This should implement #387 and #251.
In this first version I did a 1to1 sending of the script code towards the robot. If the script code contains an error, it will simply not get executed.
This could get extended in the future, but that should be an easy non-intrusive extension that gets the job done in a lot of situations.
> Urscript interface

- README.md
Before we were telling users to install the driver package only. However, it probably makes sense suggesting to install the ur meta package.
this is closing #734
> Change install instructions to install metapackage

- ur_calibration/README.md
- ur_moveit_config/launch/ur_moveit.launch.py
- ur_robot_driver/doc/setup_tool_communication.rst
- ur_robot_driver/doc/usage.rst
- ur_robot_driver/launch/ur10.launch.py
- ur_robot_driver/launch/ur10e.launch.py
- ur_robot_driver/launch/ur16e.launch.py
- ur_robot_driver/launch/ur3.launch.py
- ur_robot_driver/launch/ur3e.launch.py
- ur_robot_driver/launch/ur5.launch.py
- ur_robot_driver/launch/ur5e.launch.py
- ur_robot_driver/launch/ur_control.launch.py
This has been deprecated a while back and was never adapted. This PR goes alongside https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/77
> Use mock_hardware and mock_sensor_commands instead of fake

- ur_robot_driver/include/ur_robot_driver/urcl_log_handler.hpp
- ur_robot_driver/src/dashboard_client_node.cpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/src/urcl_log_handler.cpp
See #691 
As I do not have hardware available and also do not have the ur sim setup on this system it is currently untested.
> Introduced tf_prefix into log handler

- ur_robot_driver/doc/installation/ursim_docker.rst
- ur_robot_driver/doc/usage.rst
- ur_robot_driver/scripts/start_ursim.sh
- ur_robot_driver/test/dashboard_client.py
- ur_robot_driver/test/robot_driver.py
- ur_robot_driver/test/urscript_interface.py
This is basically to test https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/155
Keeping this draft until the client_lib is merged so we can remove the rosinstall entry.
> Start ursim from lib

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
Fix https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/778
The upcoming [Iron sync](https://discourse.ros.org/t/preparing-for-iron-sync-2023-08-25/) is blocked by [regressions](https://repo.ros2.org/status_page/ros_iron_default.html?q=REGRESSION) of these pkgs caused by API breaks from [this bump](https://github.com/ros/rosdistro/pull/38258) in `ros2_controls`.
The changes in this PR follow the upstream changes that [caused the break](https://github.com/ros-controls/ros2_controllers/pull/558/files).
> Handle api changes related to traj_external_point_ptr_

- Universal_Robots_ROS2_Driver-not-released.iron.repos
- Universal_Robots_ROS2_Driver.galactic.repos
- Universal_Robots_ROS2_Driver.iron.repos
- Universal_Robots_ROS2_Driver.rolling.repos
Some branches were not correct anymore and removed description from binary build's upstream ws.
> Fix branches of upstream workspaces for semi-binary builds

- .github/mergify.yml
Since #739 effectively is a break in the user's API we should not forward the iron branch to this change. Hence, we need to branch out and add a mergify rule to make our life easier.
I left the iron workflows running in main PRs on purpose, as in fact iron and rolling are currently still fully compatible.
> Branch out for Iron

- .github/mergify.yml
I've configured that wrong in the past. Looking at the [docs](https://docs.mergify.com/actions/backport/) this should be the correct settings.
> CI: Add labels from backports to target PR, not the original PR

- README.md
This aims at having a quick start in the README. Especially, the play step was missing before.
Closing #789
> Clarify robot startup in README

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_robot_driver/test/robot_driver.py
This is the Humble backport of #810. Since the JTC api changed on rolling recently, a direct backport isn't really applicable.
> Added a test that sjtc correctly aborts on violation of constraints

- ur_robot_driver/launch/ur_control.launch.py
As the urscript_interface tries to establish a connection to a robot we should not attempt to start it when use_mock_hardware is set to true.
Since the startup will not fail but simply block forever, I did not add a failing test beforehand.
> Do not start urscipt_interface when using mock hardware

- ur_controllers/src/gpio_controller.cpp
It does not provide a lot of value, but is printed every time the controllers are queried.
This even happens when calling `ros2 control list_controllers` or continuously while using `rqt_joint_trajectory_controller`.
> Remove noisy controller log message

- ur_moveit_config/config/ur_servo.yaml
- ur_moveit_config/launch/ur_moveit.launch.py
The moveit_servo package executable 'servo_node_main' was renamed to 'servo_node'.
> moveit_servo package executabe name has changed

- ur_robot_driver/test/dashboard_client.py
- ur_robot_driver/test/robot_driver.py
- ur_robot_driver/test/test_common.py
- ur_robot_driver/test/urscript_interface.py
Our runtime tests have accumulated quite a bit of duplicated code for starting the driver and interfacing with ROS interfaces. Before adding more tests (MoveIt, mock_hardware, ...) this should get refactored and cleaned up.
> Simplify tests

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
This will be broken soon in https://github.com/ros-controls/ros2_controllers/pull/834
> Renamed normalize_joint_error_ to joints_angle_wraparound_

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/urdf/ur.ros2_control.xacro
- ur_robot_driver/urdf/ur.urdf.xacro
This goes along https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/114
Basically, this will draw all driver-relevant parts to this repo which will make adding new functionalities a lot easier and more consistent.
> Add control description and ros2_control tag to driver.

- README.md
- ur_moveit_config/launch/ur_moveit.launch.py
- ur_robot_driver/config/test_goal_publishers_config.yaml
- ur_robot_driver/config/ur30_update_rate.yaml
- ur_robot_driver/doc/usage.rst
- ur_robot_driver/launch/ur30.launch.py
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/test/test_common.py
> Add UR30 support

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
This should fix the semi-binary builds (and future testing builds) on Humble.
> Update JTC API

- ur_moveit_config/launch/ur_moveit.launch.py
fix #903
Moveit2 recently refactored planning pipeline, we need to change the config file correspondingly. See https://github.com/ros-planning/moveit2/blob/1fb4041e690c64b847d2df1e844c8de148796c86/MIGRATION.md
- Change planning plugin to a list of plugins, according to the change introduced in 10/2023 in moveit rolling.
- Split request_adapters to request_adapters and response_adapters, according to the refactor of planning pipeline introduced in 10/2023 in moveit rolling.
I tested it locally with URSim. Planning and execution works well.
> fix move_group_node crash during initialization

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
Corrects point of initialization / connection to the robot by moving it to `on_configure` instead of `on_activate`.
@destogl we talked about this yesterday, I found my commit I had in mind :-)
> Move communication setup to on_configure instead of on_activate

- ur_robot_driver/launch/ur20.launch.py
Currently the UR20 is the only one using "use_mock_hardware" and since the description pkg for humble still has "use_fake_hardware", it doesn't work launching it with the mock_hardware option. 
Maybe it's better to have fake_hardware also for the UR20 and in the future switch all the models together when fake_hardware can't be used anymore.
Also, the same goes for iron, so if this makes sense I will open a PR for the iron branch as well.
> Switch to "use_fake_hardware" for UR20

- ur_robot_driver/doc/installation/installation.rst
I think there is some information missing, if someone wants to build the driver from source on a non-rolling ROS distro.
Relates to https://robotics.stackexchange.com/questions/110644/ros2-ur-driver-package-failed-ur-controllers/110654#110654
> Update installation instructions for source build

- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/launch/ur_rsp.launch.py
Doing this should greatly improve usability in cases where people want to specify their own description.
With this change, we can e.g. specify our own description using something like
```
ros2 launch ur_robot_driver ur_control.launch.py description_launchfile:=$(ros2 pkg prefix my_robot_cell_control)/share/my_robot_cell_control/launch/rsp.launch.py robot_ip:=123 use_mock_hardware:=true ur_type:=ur20 tf_prefix:=ur20_
```
This was developed during finishing https://github.com/UniversalRobots/Universal_Robots_ROS_Tutorials/pull/12
> Move starting the robot_state_publisher to an own launch file

- .github/workflows/reusable_ici.yml
- ur_robot_driver/package.xml
The dependency was basically added since this is needed to spawn up ursim. However, the start_ursim script catches the case that no docker executable is available and the tests requiring it are behind a compile definition which is off by default.
So, in order to not install docker for users automatically, the dependency shall be removed.
As a side-effect this has always stopped us from releasing the package for RHEL.
This closes #769
> Remove dependency to docker.io

- ur_controllers/src/gpio_controller.cpp
> [GPIO Controller] Use latched publishing for robot_mode and safety_mode

- ur_bringup/launch/ur_control.launch.py
- ur_robot_driver/launch/ur_control.launch.py
At the moment passing the robot calibration as launch argument is not possible in Humble, but only on Rolling. These changes allow that and they should also fix [#918](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/918).
> Add calibration file to launch arguments

- ur_bringup/launch/ur_control.launch.py
Since `ur_control.launch.py` from `ur_bringup` is basically a duplicate of the one contained in `ur_robot_driver`, this PR makes it much simpler by reusing what is already defined in the other launch file, avoiding useless repetitions.
> Simplify launch file for ur_bringup pkg

- ur_robot_driver/doc/migration/jazzy.rst
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/urdf/ur.ros2_control.xacro
The `keepalive_count` has been deprecated in the ur_client_library for quite some time now. This PR removes it also from the driver and replaces it by `robot_receive_timeout`.
Note: This cannot be directly backported, since for iron and humble we need to do it backwards-compatible. I will provide a separate PR for this.
> Replace keepalive count

- ur_robot_driver/test/test_common.py
With those extra spaces the input isn't correctly parsed.
This is basically why the tests in #1009 are failing as that particular version of the script in the client library fails on a non-given model.
> Remove extra spaces from start_ursim statement in tests

- ur_moveit_config/config/ur_servo.yaml
Disables the servo node from advertising `/get_planning_scene`, which in the default launchfile, conflicts with `move_group`'s `/get_planning_scene`. See https://github.com/moveit/moveit2/issues/2731 for discussion.
Tested on a Humble branch.
> Add servo node config to disable advertising /get_planning_scene

- ur_robot_driver/launch/ur_control.launch.py
This is now part of ur_rsp.launch.py
> Remove tf_prefix from ur_control.launch.py

- ur_moveit_config/CMakeLists.txt
Since we use the srdf from that folder, we should also install that.
This was broken in #998.
> Also install srdf folder

- ur_robot_driver/src/controller_stopper.cpp
Fixes the issue reported in #1037 
I've chosen a rather arbitrary 100ms of sleep. Maybe a shorter period would be desirable to avoid "long" periods where the controller seems to be running?
@kjjpc do you have an opinion on the sleep period?
> Add sleep between controller stopper's controller queries

- ur_robot_driver/doc/migration/jazzy.rst
> Add migration notes for jazzy

- ur_robot_driver/doc/installation/robot_setup.rst
this seems like it was never updated. We should think about linking this to the library's requirement section, but this is a quick fix for now.
> [doc] Update required polyscope version

- README.md
This PR specifies that the driver requires a Linux OS to work, improving in clarity for doubts about a possible Windows support [#549 ](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/549).
> [doc] Note about required OS

- ur_robot_driver/doc/usage.rst
It was pointed out to us that the test node's source code wasn't linked. There is a link, but the test node has actually been moved. This PR updates the documentation on that.
> [doc] Update reference to ros2_controllers test node

- ur_robot_driver/doc/usage.rst
Seems to be an important detail missing that the custom URScript command only works in headless mode
> Add doc to custom URScript commands that it needs to be in headless mode

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/test/launch_args.py
- ur_robot_driver/test/test_common.py
This was not handled properly.
This fixes #1056
> Fix passing launch_dashobard_client launch argument

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
This should fix the current builds and #1062.
> Updated scaled JTC to latest JTC updates

- ur_moveit_config/doc/migration/jazzy.rst
This PR addresses [#1048](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/1048) and tries to summarize the important changes for the `ur_moveit_config` package from a user perspective.
> [doc] Add Jazzy migration notes for moveit_config

- ur_robot_driver/urdf/ur.ros2_control.xacro
This goes in line with https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/175
> Added dynamics tag when using mock_components/GenericSystem

- ur/package.xml
- ur_calibration/package.xml
- ur_controllers/package.xml
- ur_dashboard_msgs/package.xml
- ur_robot_driver/package.xml
Since I am going through the steps of doing a binary release of the [GZ simulation package](https://github.com/UniversalRobots/Universal_Robots_ROS2_GZ_Simulation), I need first of all to be added into the release team on `ros2-gbp` and, to create an issue for that, it's necessary to show that you belong to the maintainers team. 
So I updated things around also moving Robert to the authors section :)
> Update maintainers team

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
This PR updates the name of `get_state()` according to the [commit](https://github.com/ros-controls/ros2_controllers/commit/ce12694c6c948509a470783fd3b770cfab60a26e) that changes it to `get_lifecycle_state()` in ros2_controllers. In this way the CI for rolling and jazzy (Semi Binary) won't fail during building.
> Update get_state to get_lifecycle_state

- ur_robot_driver/config/test_velocity_goal_publishers_config.yaml
- ur_robot_driver/launch/test_forward_velocity_controller.launch.py
This PR aims to fix the test for the `forward_velocity_controller`: basically the related config file was missing the `publish_topic` parameter. Now when the controller is active, the velocity goals are correctly sent by launching `test_forward_velocity_controller.launch.py`.
> Fix for forward_velocity_controller test

- ur_moveit_config/launch/ur_moveit.launch.py
Added argument to the launch file that can toggle the ability to publish the contents of the SRDF on the topic /robot_description_semantic. This allows the launch file to be used with custom moveit2 projects without having to source the SRDF for every launched node.
See following link for details: https://moveit.picknik.ai/humble/doc/examples/urdf_srdf/urdf_srdf_tutorial.html#string-topic-specification
Note: The default behaviour of not publishing this topic has been maintained, but now users have the option publish it if needed.
> Added option to publish SRDF file.

- ci_status.md
The status page for the Jazzy binary packages was missing referring to the Rolling packages instead of Jazzy.
Rbin -> Jbin
> Fix ci_status package reference for Jazzy

- ur_robot_driver/launch/ur_rsp.launch.py
If this isn't explicitly specified, the description string might be interpreted as a yaml content, which leads to problems, obviously.
This was mentioned in #1103 and needs to get backported. However, since we refactored loading the description this will not be a straightforward backport, I'll open a separate PR.
> Assure the description is loaded as string

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
As this has been added in the joint description, we need to also parse them from the hardware interface.
This is a part of #944 that is necessary since https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/204 is merged.
This should also fix the current semi-binary failures.
> Add passthrough interfaces for joints

- ur_controllers/doc/index.rst
- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/src/gpio_controller.cpp
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/urdf/ur.ros2_control.xacro
This basically implements a service for https://github.com/ros-industrial/ur_msgs/pull/30
> Allow setting the analog output domain when setting an analog output

- ur_moveit_config/launch/ur_moveit.launch.py
Same as #1133, but targeting iron
> [moveit] Disable execution_duration_monitoring by default

- ur_moveit_config/config/moveit_controllers.yaml
- ur_moveit_config/doc/index.rst
- ur_robot_driver/doc/usage/move.rst
> Add note about TEM

- .github/helpers/check_urls.sh
- .github/workflows/check_links.yml
- README.md
Update broken links from README and add a URL checker to CI.
> Readme update hosted docs

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
This reverts commit 3068607b1de03a6e6a4687a3da51b694449794a6.
Complementing https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/214
I had a bad feeling about this and hence also only released it to rolling. Thinking about this a bit, it occurred to me that -- since we want to send other motion types in the future -- it doesn't make sense necessarily to add this to the joints.
> Revert "Add passthrough interfaces for joints (#1121)"

- ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.hpp
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
This way, the controller can be used on systems, where no scaling interface is available (e.g. GZ). The upstream version in ros2_controllers will have the same behavior.
This is a part of fixing https://github.com/UniversalRobots/Universal_Robots_ROS2_GZ_Simulation/issues/57
> [SJTC] Make scaling interface optional

- README.md
Centered and increased size of family photo
> Adjust alignment and size of family photo 

- ur_moveit_config/launch/ur_moveit.launch.py
When running with sim_time, we need to pass that to the RViz instance, as well.
This is a part of fixing https://github.com/UniversalRobots/Universal_Robots_ROS2_GZ_Simulation/issues/57
> Pass `use_sim_time` to MoveIt's RViz instance

- .github/workflows/check_links.yml
When adding the link checks in #1137, this actually slipped through.
> Disable link checks for architecture_coarse.svg

- ur_moveit_config/launch/ur_moveit.launch.py
Pass use_sim_time also to RViz and use non-scaled JTC when use_sim_time is active.
This is basically a manual backport of #1144
@Mergifyio backport humble
> [moveit] Properly handle use_sim_time

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver.humble.repos
Update the upstream workspace regarding
- Add realtime_tools from ros-controls
- Update branch of kinematics_interface to humble as the master version got API incompatible
- Make upstream ws for binary build empty
> Update Humble upstream workspace

- .github/workflows/humble-binary-main.yml
- .github/workflows/humble-binary-testing.yml
- .github/workflows/humble-semi-binary-main.yml
- .github/workflows/humble-semi-binary-testing.yml
- .github/workflows/iron-binary-main.yml
- .github/workflows/iron-binary-testing.yml
- .github/workflows/iron-semi-binary-main.yml
- .github/workflows/iron-semi-binary-testing.yml
- .github/workflows/jazzy-binary-main.yml
- .github/workflows/jazzy-binary-testing.yml
- .github/workflows/jazzy-semi-binary-main.yml
- .github/workflows/jazzy-semi-binary-testing.yml
- .github/workflows/reusable_ici.yml
- .github/workflows/rolling-binary-main.yml
- .github/workflows/rolling-binary-testing.yml
- .github/workflows/rolling-semi-binary-main.yml
- .github/workflows/rolling-semi-binary-testing.yml
- Universal_Robots_ROS2_Driver.jazzy.repos
- Universal_Robots_ROS2_Driver.rolling.repos
The recent upstream changes in ros2_control revealed some tech debt on our workflows. This PR updates them regarding
- Proper naming of jobs for clearer identification
- Correct naming of steps in reusable ici
- Adding missing upstream packages from ros2_control in upstream workspaces
- Fix workflow syntax in some places
- Add ccache
- Add MoveIt to upstream workspace -- this avoids installing ros2_control from binary packages.
> Cleanup workflows

- ur_calibration/include/ur_calibration/calibration.hpp
Also add missing #include <cassert>
> Initialize segments in constructor of DHRobot in calibration.hpp

- Universal_Robots_ROS2_Driver.jazzy.repos
- Universal_Robots_ROS2_Driver.rolling.repos
Currently, the semi-binary jobs are failing because ros2_controllers need a new class from control_toolbox.
> Add control_toolbox to semi-binary repos files

- Universal_Robots_ROS2_Driver.humble.repos
> Add control_toolbox to semi-binary repos file

- ur_controllers/src/passthrough_trajectory_controller.cpp
The rolling version of ros2_control is kept compatible for compiling on humble distro. Obviously, I need to compile the rolling UR driver on humble too:
There exists no `+=` overload for `rclcpp::Duration` class on humble, which was introduced later https://github.com/ros2/rclcpp/pull/1988
We can use the rclcpp/version.h, or we could also just use the manual assignment.
> Make ur_controllers compileable on humble

- ur_robot_driver/doc/installation/robot_setup.rst
- ur_robot_driver/doc/usage/startup.rst
Added to / modified documentation to make it more clear how to utilize extracted calibration information, and how to verify that the information is being utilized. Also clarified that the robot must be on to extract calibration info.
I added a description of the parameter-passing method, but not the "create your own description package and use that" method. That seemed a little too in-depth and unnecessary for the getting started documentation, when the parameter method will work for most cases. But if I'm missing something, maybe we want to describe the second method as well.
Related issues: #799
> improve docs around usage of extracted calibration info

- ur_controllers/package.xml
Currently, our buildfarm builds fail for Humble, but it should also be fixed for the main branch.
> Add missing test dependencies for ur_controllers

- ur_robot_driver/launch/ur_control.launch.py
> Disable pose broadcaster on mock hardware

- .pre-commit-config.yaml
- ur_bringup/CHANGELOG.rst
- ur_controllers/CHANGELOG.rst
- ur_robot_driver/CHANGELOG.rst
This should also work on humble and give us a solid baseline to backport any future updates of the main pre-commit config.
> Update pre-commit the same as on the main branch

- ur_moveit_config/launch/ur_moveit.launch.py
I don't quite know why this was still used. I could not replicate when we started the non-scaled JTC for fake hw while we were launching the scaled JTC for the real robot. However, we were differentiating between the two in the MoveIt startup.
From my understanding and my local testing this is not necessary, but is in fact stopping the MoveIt setup from working out of the box.
This is also related to #1236
> ur_moveit_config: Do not change default controller when using fake hardware

- ur_controllers/include/ur_controllers/force_mode_controller.hpp
- ur_controllers/include/ur_controllers/freedrive_mode_controller.hpp
- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/include/ur_controllers/passthrough_trajectory_controller.hpp
- ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.hpp
- ur_controllers/include/ur_controllers/speed_scaling_state_broadcaster.hpp
- ur_controllers/include/ur_controllers/ur_configuration_controller.hpp
- ur_controllers/package.xml
- ur_controllers/src/force_mode_controller.cpp
- ur_controllers/src/freedrive_mode_controller.cpp
- ur_controllers/src/gpio_controller.cpp
- ur_controllers/src/passthrough_trajectory_controller.cpp
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_controllers/src/ur_configuration_controller.cpp
This PR aims at reducing the build warnings to 0.
> Remove all build warnings

- ur_robot_driver/doc/make.bat
Fix sphinx doc link in ur_robot_driver to make the pipeline green again
> fix sphinx doc link in ur_robot_driver

- ur_robot_driver/test/integration_test_force_mode.py
The lookup can result in quaternions that look different component-wise while still being very similar. Instead of comparing them component-wise to decide whether they are similar, we check whether their dot-product is equal to 1.0. That should be more robust.
> Check quaternions for equal dot_product instead of comparing their components individually

- ur_controllers/include/ur_controllers/force_mode_controller.hpp
- ur_controllers/include/ur_controllers/freedrive_mode_controller.hpp
- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/include/ur_controllers/passthrough_trajectory_controller.hpp
- ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.hpp
- ur_controllers/include/ur_controllers/speed_scaling_state_broadcaster.hpp
- ur_controllers/include/ur_controllers/ur_configuration_controller.hpp
- ur_controllers/package.xml
- ur_controllers/src/gpio_controller.cpp
- ur_controllers/src/ur_configuration_controller.cpp
- ur_robot_driver/src/ur_ros2_control_node.cpp
This PR aims at removing all build warnings for Humble.
Waiting for realtime-tools to be released before this is ready-to-review.
> Remove build warnings for Humble

- README.md
The respective URCap installation setup got merged into the robot_setup in the client_library's documentation.
> Fix broken link to robot_setup in README

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
We did not have the on_shutdown method implemented which gets called by the resource manager when shutting down. This could potentially result in crashes or pipeline overflows when shutting down the control node.
There was an intermediate fix calling on_cleanup in the destructor, which isn't correct either. That got deleted.
> Fix crashes on shutting down

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
See https://github.com/ros-controls/ros2_controllers/pull/1032
> Apply renaming of member variables of JTC

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
The former has been marked deprecated in control_toolbox.
> Update computeCommand to compute_command

- ur_controllers/src/gpio_controller.cpp
This would be needed in order to have the controllers compiling with the future API of Handles with variants
> Cast to double for future variant API

- ur_robot_driver/doc/dashboard_client.rst
The URLs to the generated message definitions have changed.
This should fix the check_links job.
> Update message documentation URLs

- ur_controllers/CMakeLists.txt
- ur_controllers/src/force_mode_controller.cpp
- ur_controllers/src/freedrive_mode_controller.cpp
- ur_controllers/src/gpio_controller.cpp
- ur_controllers/src/passthrough_trajectory_controller.cpp
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_controllers/src/speed_scaling_state_broadcaster.cpp
- ur_controllers/src/ur_configuration_controller.cpp
Update to new `get_optional` API from ros2_control. Let's try to keep the warnings at 0.
> Update ros2_control API to get_optional

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/resources/rtde_output_recipe.txt
- ur_robot_driver/src/hardware_interface.cpp
The force torque is returned at the tool flange on e-series robots and at the tcp for CB3, this is now handled correctly, so that all force/torque measurements will be relative to the active TCP
> Update transformForceTorque to handle wheter it is a cb3 or an e-Series robot

- Universal_Robots_ROS2_Driver.jazzy.repos
- Universal_Robots_ROS2_Driver.rolling.repos
ros2_controls branched out a couple of packages for Jazzy. This doesn't necessarily mean that we have to branch out, too, but we should adapt in the upstream workspaces for the semi-binary builds. This way we will see when they diverge in an API-incompatible manor.
> Update upstream workspace to branched out jazzy versions

- ur_robot_driver/doc/usage/controllers.rst
Velocity and position was mixed up in the links.
Fixes https://github.com/UniversalRobots/Universal_Robots_ROS2_Documentation/issues/3
> Fix links to forward command controllers

- ur_controllers/src/passthrough_trajectory_controller.cpp
- ur_robot_driver/test/robot_driver.py
When specifying higher-order splines while no velocity or acceleration state interfaces are configured for the robot, the controller attempted to read from the non-existing interfaces. This PR adds a check whether those interfaces are actually configured before attempting to read from them.
> Fix passthrough controller to not read non-existing state_interfaces

- ci_status.md
The builds have been removed in 077bac55d909a1759e54d16d222ce8ece3be882e
In #1315 we missed that as the links were still existing there.
> Remove semi-binary testing builds from ci_status

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/include/ur_robot_driver/dashboard_client_ros.hpp
- ur_robot_driver/include/ur_robot_driver/robot_state_helper.hpp
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/src/dashboard_client_node.cpp
- ur_robot_driver/src/dashboard_client_ros.cpp
- ur_robot_driver/src/robot_state_helper.cpp
- ur_robot_driver/src/robot_state_helper_node.cpp
Since PolyScopeX robots don't have a dashboard server, we'll have to make sure to
a) not start the dashboard client when interacting with a PolyScopeX robot
b) replace the robot_state_helper's functions to the dashboard server with primary_client API calls.
This requires https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/296 to work.
> Support PolyScopeX robots

- ur_controllers/include/ur_controllers/passthrough_trajectory_controller.hpp
- ur_controllers/src/passthrough_trajectory_controller.cpp
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/urdf/ur.ros2_control.xacro
When transferring trajectories with many waypoints it can take quite a
while until all points are transferred from the controller to the
hardware interface, especially on lower hardware_interface update rates.
With this change, execution starts as soon as enough trajectory points
are transferred to fill 5 control cycles.
This PR effectively allows reducing the hardware_interface update_rate
when using the passthrough_trajectory_controller significantly. This
will reduce the networking requirements improving the overall user
experience.
> Start executing passthrough trajectories earlier than all points are transferred.

- ur_calibration/doc/algorithm.rst
- ur_calibration/doc/index.rst
- ur_calibration/doc/usage.rst
- ur_controllers/doc/index.rst
- ur_moveit_config/doc/index.rst
- ur_moveit_config/doc/migration/jazzy.rst
- ur_robot_driver/doc/controller_stopper.rst
- ur_robot_driver/doc/dashboard_client.rst
- ur_robot_driver/doc/features.rst
- ur_robot_driver/doc/hardware_interface_parameters.rst
- ur_robot_driver/doc/index.rst
- ur_robot_driver/doc/installation/installation.rst
- ur_robot_driver/doc/installation/robot_setup.rst
- ur_robot_driver/doc/installation/toc.rst
- ur_robot_driver/doc/migration/jazzy.rst
- ur_robot_driver/doc/operation_modes.rst
- ur_robot_driver/doc/overview.rst
- ur_robot_driver/doc/robot_state_helper.rst
- ur_robot_driver/doc/setup_tool_communication.rst
- ur_robot_driver/doc/usage/controllers.rst
- ur_robot_driver/doc/usage/move.rst
- ur_robot_driver/doc/usage/script_code.rst
- ur_robot_driver/doc/usage/simulation.rst
- ur_robot_driver/doc/usage/startup.rst
- ur_robot_driver/doc/usage/toc.rst
This way the "Edit on GitHub" links in the assembled documentation work correctly.
> Add github_url directives to all rst files

- ur_robot_driver/test/integration_test_tool_contact.py
Re-using the goal handle seems to be flaky.
> tool_contact_test: Check result status directly

- ur_robot_driver/src/hardware_interface.cpp
Before the main control mode (position/velocity) was always overwriting the complete list for the joint. That worked fine when that was the only control mode for a joint or if it was the first in the list. But that is not guaranteed.
Since we create the list as an empty vector beforehand, anyway, we can simply append to that list in any case. The list will be checked for compatibility at a later point, anyway.
> Only append to start_modes in prepare_switch

- ur_robot_driver/doc/usage/toc.rst
It happens frequently that people run into symbol lookup errors due to ABI breaks. This section should give them something to do on that.
e.g. https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/791#issuecomment-1715630184
> Add troubleshooting section about handling ABI breaks

- ur_robot_driver/config/test_goal_publishers_config.yaml
- ur_robot_driver/doc/usage/move.rst
- ur_robot_driver/launch/test_joint_trajectory_controller.launch.py
- ur_robot_driver/launch/test_scaled_joint_trajectory_controller.launch.py
This should allow to use them in situations, where the robot is not at the preconfigured pose, but users understand the risks and want to circumvent this.
Also, I updated the documentation around this.
> Make check_starting_point of test_move launch files configurable

- ur_controllers/include/ur_controllers/scaled_joint_trajectory_controller.hpp
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
This basically changes things to what I currently have in https://github.com/ros-controls/ros2_controllers/pull/1191 hoping that this will finally get to a mergable point.
> SJTC: Update to latest upstream JTC API

- .github/workflows/jazzy-binary-main.yml
- .github/workflows/jazzy-binary-testing.yml
- .github/workflows/jazzy-semi-binary-main.yml
- README.md
- Universal_Robots_ROS2_Driver.jazzy.repos
- ci_status.md
The changed API of the upstream JTC (see #1362) forces us to branch for Jazzy.
> Branch jazzy

- .github/release.yml
Github allows customizing the auto-generated changelogs. This is a first attempt to configure that.
> Add a release config file for GitHub release note auto-generation

- ur_calibration/CMakeLists.txt
- ur_calibration/src/calibration_correction.cpp
- ur_controllers/CMakeLists.txt
- ur_robot_driver/CMakeLists.txt
ament_target_dependencies has become deprecated with ROS Kilted and raises an error for ROS Rolling. This replaces the deprecated calls by modern CMake target_link_libraries calls instead.
> Replace ament_target_dependencies calls

- ur_controllers/src/force_mode_controller.cpp
- ur_robot_driver/examples/force_mode.py
- ur_robot_driver/test/integration_test_force_mode.py
Before, we were using a RPY notation. Changing that to an angle-axis notation should fix things.
This should fix #1375 
@bsolon-tri would you like to try that locally?
I want to add a test checking further orientations and an updated example before merging this, but testing things locally seem to have resolved the issue.
> [force mode controller] Fix the task frame orientation

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
The upstream API isn't finalized, yet. For now, let's ignore the deprecation warning in order to not fail our builds.
As discussed in https://github.com/ros-controls/control_toolbox/issues/392 the API change isn't final, yet.
> Ignore deprecation warning for set_gains for now

- .pre-commit-config.yaml
This will not require users to have a specific clang-format version installed. Also, this will be updated automatically, so we are not stuck with an old clang-format version. If formatting changes come in from a newer clang-format version, we can adapt our config whenever that happens.
> Use the Python mirror for clang-format in pre-commit config

- ur_controllers/CMakeLists.txt
The package compiles a library, but does not expose any symbol on Windows, so if the CMake project is compiled on  on Windows, no library is actually generated.
On Linux and macOS, everything compiles by default all the symbols are visible. We can achieve exactly the same behavior in Windows by setting to `ON` the [`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`](https://cmake.org/cmake/help/v3.4/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html) CMake variable, so this PR sets the `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` variable to `ON`, to ensure that the compilation works fine on Windows.
Furthermore, the `-Wpedantic -Werror` are GCC/Clang specific compilations options, so I moved it in an `if` for adding GCC/Clang specific compilations options.
> ur_controllers: Fix compilation on Windows

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
Once https://github.com/ros-controls/ros2_controllers/pull/1759 and https://github.com/ros-controls/control_toolbox/pull/400 is merged.
Fixes https://github.com/ros-controls/control_toolbox/issues/392
> Use new API of PID class

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
Refactored prepare_switch mechanism. This way it should be easier to understand and to extend.
> Refactor prepare_switch method

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/src/robot_state_helper.cpp
The package compiles a library, but does not expose any symbol on Windows, so if the CMake project is compiled on  on Windows, no library is actually generated.
On Linux and macOS, everything compiles by default all the symbols are visible. We can achieve exactly the same behavior in Windows by setting to `ON` the [`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`](https://cmake.org/cmake/help/v3.4/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html) CMake variable, so this PR sets the `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` variable to `ON`, to ensure that the compilation works fine on Windows.
Furthermore, the following fixes were also added:
* `-Wall -Wextra` are GCC/Clang specific compilations options, so I moved it in an `if` for adding GCC/Clang specific compilations options.
* `uint` does not exists in …
> ur_robot_driver: Fix compilation on Windows

- ur_robot_driver/config/ur_controllers.yaml
Since the upstream JTC supports scaling by know, we can start adding the state interface to the controller.
> Add scaling parameters to upstream JTC

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
The preferred signature of hardware_interface::on_init has been changed upstream. This change avoids a deprecation warning on that.
> Migrate hardware_interface's on_init method

- ur_controllers/include/ur_controllers/ur_configuration_controller.hpp
- ur_controllers/src/ur_configuration_controller.cpp
Using set could potentially block the RT thread.
Also, realtime_tools have changed their API regarding the `set` function not to accept a call by value to a pointer anymore, so we have to touch this anyway.
> ur_configuration_controller: use try_set on RTBox

- ur_controllers/include/ur_controllers/force_mode_controller.hpp
- ur_controllers/include/ur_controllers/passthrough_trajectory_controller.hpp
- ur_controllers/include/ur_controllers/tool_contact_controller.hpp
- ur_controllers/include/ur_controllers/ur_configuration_controller.hpp
- ur_controllers/src/force_mode_controller.cpp
- ur_controllers/src/passthrough_trajectory_controller.cpp
- ur_controllers/src/tool_contact_controller.cpp
- ur_controllers/src/ur_configuration_controller.cpp
Changes all our `realtime_tools` containers to `RealtimeThreadSafeBox`, seems like that is fine everywhere. 
Also made it so that any reading or writing done outside of real-time threads will retry 10 times before failing.
> Realtime tools migration
