UniversalRobots/Universal_Robots_ROS2_Driver

- ur_description/launch/view_ur5.launch.py
- ur_description/urdf/ur5.urdf.xacro
- ur_description/urdf/ur5_joint_limited_robot.urdf.xacro
- ur_description/urdf/ur5_robot.urdf.xacro
Change launch file to parse xacro file and set the `robot_description` parameter. Remove decimals places from the xacro file and replace it with built-in property.
> Make xacro property propagate to robot_description

- ur_description/launch/view_ur5.launch.py
- ur_description/urdf/ur5.urdf.xacro
- ur_description/urdf/ur5_joint_limited_robot.urdf.xacro
- ur_description/urdf/ur5_robot.urdf.xacro
I didn't notice that PR #9 was targeted on a branch other than `develop`. This simply cherry-picks it to `develop` instead
@livanov93 please review and merge if it looks OK
> Make xacro property propagate to robot_description (#9)

- README.md
> Improve README for testing purposes

- ur_robot_driver/include/ur_robot_driver/hardware_interface.h
- ur_robot_driver/src/hardware_interface.cpp
This PR removes all velocity command interface stuff on actively developed branch as a result of milestones for Beta driver release.
> Use only position command interface for Beta driver

- ur_controllers/CMakeLists.txt
- ur_controllers/controller_plugins.xml
- ur_controllers/include/ur_controllers/speed_scaling_state_controller.h
- ur_controllers/package.xml
- ur_controllers/src/speed_scaling_state_controller.cpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_ros2_control_demos/config/ur_ros2_control.yaml
Controller is base on the current joint_state_controller of ros2 control
Missing Features:
> SpeedScalingStateController

- README.md
Addresses my concern here:
https://github.com/PickNikRobotics/Universal_Robots_ROS2_Driver/pull/41/files
> Restore note on org ownership

- ur_robot_driver/src/hardware_interface.cpp
> Move to home bug

- README.md
- ur_bringup/launch/ur_control.launch.py
- ur_bringup/launch/ur_moveit.launch.py
This adds an argument for RViz launching and updates the README about it.
Also, I changed some numbers in the README to bullet points since they don't really need to be traversed in order anymore.
> Make an optional launch arg for RViz, document it in README

- README.md
- ur_bringup/launch/ur_control.launch.py
- ur_description/launch/view_ur.launch.py
> Added view_ur for checking description

- README.md
> Add documentation for hardware setup 

- ur_controllers/src/gpio_controller.cpp
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
> Setting speed slider with range of 0.0-1.0 and added warnings if range is exceeded

- Universal_Robots_ROS2_Driver.repos
- ur_robot_driver/resources/ros_control.urscript
> Using official Universal Robot Client Library

- README.md
- ur_robot_driver/resources/Dockerfile
* Updated README to reflect transfer to Universal Robots GitHub
* This is related to the discussion in #96
> Added dockerfile for the driver

- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/src/gpio_controller.cpp
- ur_description/urdf/ur.ros2_control.xacro
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
> Fixed speed slider service call

- README.md
- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/src/gpio_controller.cpp
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
- Add pin labels (#98)
- Teachpanel and Services can no interchangeably adjust the GPIOs (#87)
> Fix gpio controller

- ur_bringup/launch/ur_control.launch.py
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
> Removed dashboard client from hardware interface

- Universal_Robots_ROS2_Driver.repos
- ur_bringup/config/ur_controllers.yaml
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
I just unintentionally pushed the wrong chagnes to kbogert:main branch and than closed #121.
Here all the changes with (see the last commit):
- rebased to main
- formatting fixed
- added include of std::vector
No functionality was changed compared to tested version of #121.
Learning: always create a feature branch for PRs (@kbogert)
@MGBla and @AdamPettinger: can you do the review one more time? (Testing with HW is probably not necessary).
@kbogert: a backup of your original branch is [here](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/kbogert-main-bkp)
> Updated Changes on JointTrajetoryController from #121

- README.md
Thanks to @xi-hhhm for the feedback!
> Add manual updates from users feedback.

- ur_description/urdf/inc/ur_common.xacro
> Fix invalid xacro properties

- Universal_Robots_ROS2_Driver.repos
Update control_msgs to track galactic branch (#169)
> Update conrol_msgs branch in Universal_Robots_ROS2_Driver.repos

- MoveIt_Support.repos
- ur_description/urdf/inc/ur_common.xacro
Change moveit2 branch in .repos file for moveit support.
> Change moveit2 branch.

- Universal_Robots_ROS2_Driver.repos
Use foxy branch of ros2_control_demos.
> Master will start braking soon

- ur_bringup/launch/ur_control.launch.py
- ur_moveit_config/config/ur_servo.yaml
- ur_moveit_config/launch/test_moveit_servo_velocity_controller.launch.py
- update the publish_period. 50 Hz is too slow for UR robots, it seems.
- launch a Servo node rather than a pose tracker node. Pose tracking is a little more specialized and complicated, so I don't think it's needed for this demo launch file
https://user-images.githubusercontent.com/11284393/134968581-512d244d-a952-4c0a-869b-0916247f4ac3.mp4
> Update Servo parameters, for smooth motion

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
Needed after ros-controls/ros2_control#503.
> Add breaking api changes from ros2_control to hardware_interface

- ur_bringup/launch/ur_control.launch.py
It is implemented two lines above...
> Remove obsolete comment 🐒

- .github/workflows/foxy-source-build.yml
Resolves #271
@urrsk we should try to merge this and then wait a day to see if everything gets green.
> Fix foxy source build to use correct .repos file

- Universal_Robots_ROS2_Driver-not-released.galactic.repos
Should we do the same for rolling?
> Updated list of released packages for galactic

- ur_robot_driver/src/hardware_interface.cpp
Fixes #258 and needs UniversalRobots/Universal_Robots_ROS2_Description#12
> Change driver constructor and change calibration check

- .pre-commit-config.yaml
> Fix precommit black foxy

- .github/workflows/galactic-binary-build.yml
- .github/workflows/galactic-semi-binary-build.yml
- .github/workflows/rolling-binary-build.yml
- .github/workflows/rolling-semi-binary-build.yml
- .github/workflows/test-ci.yml
Do not fail fast in CI runs. We'd like to know if it is just  a flaw in the testing repos or if there is something wrong with main.
> Ci do not fail fast

- ur_moveit_config/package.xml
> Add missing dep to warehouse_ros_mongo

- README.md
The image got moved to another folder in #340 .
> Fixed image path on README

- README.md
> Update package list in top-level README

- .github/workflows/galactic-binary-build.yml
- Universal_Robots_ROS2_Driver-not-released.galactic.repos
- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- ur_controllers/CMakeLists.txt
- ur_controllers/package.xml
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
Most dependencies have actually been released by now...
Closing #341
> Update binary dependencies

- ur_bringup/package.xml
- ur_calibration/package.xml
- ur_controllers/package.xml
- ur_dashboard_msgs/package.xml
- ur_moveit_config/package.xml
- ur_robot_driver/doc/resources/README.md
- ur_robot_driver/package.xml
Corrected tag order according to schema while at it.
@destogl I assume you'd like to keep being listed as a maintainer. Which mail address should I use for that?
> Updated package maintainers

- .github/workflows/foxy-binary-build.yml
- .github/workflows/foxy-semi-binary-build.yml
- .github/workflows/foxy-source-build.yml
Obviously I was not aware that workflow definitions have to reside on the main branch...
> Re-add foxy builds to main branch

- ur_bringup/launch/ur_control.launch.py
- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/src/gpio_controller.cpp
- ur_description/urdf/ur.ros2_control.xacro
- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/README.md
- ur_robot_driver/include/ur_robot_driver/controller_stopper.hpp
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/controller_stopper.cpp
- ur_robot_driver/src/controller_stopper_node.cpp
- ur_robot_driver/src/hardware_interface.cpp
Backport of #309 
This is currently a draft, as I haven't tested it, yet.
> Foxy controller stopper

- .github/workflows/foxy-source-build.yml
The URL specified in #364 was not correct for the raw file.
> Correct foxy source build repos file

- .github/workflows/coverage-build.yml
- .github/workflows/rolling-source-build.yml
> Fix coverage build

- README.md
The installation documentation got moved by #340
> Fix README links to installation documentation

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
- ur_robot_driver/src/ur_ros2_control_node.cpp
Update hardware interface API changed in ros-controls/ros2_control#715
> Update HW-interface API for humble.

- ur_bringup/package.xml
- ur_controllers/CMakeLists.txt
- ur_controllers/package.xml
- ur_moveit_config/package.xml
- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/package.xml
This is basically a backport from #391
> Fix dependencies for galactic

- ur_bringup/launch/test_forward_velocity_controller.launch.py
- ur_bringup/launch/test_joint_trajectory_controller.launch.py
- ur_bringup/launch/test_scaled_joint_trajectory_controller.launch.py
- ur_bringup/launch/ur_control.launch.py
- ur_calibration/CMakeLists.txt
- ur_calibration/launch/calibration_correction.launch.py
- ur_controllers/CMakeLists.txt
- ur_moveit_config/launch/ur_moveit.launch.py
- ur_robot_driver/CMakeLists.txt
These changes allow me to run the driver on humble
> Prepare for humble

- ur_bringup/config/ur_controllers.yaml
This is one part of the current execution test CI failures
> Fix force_torque_sensor_broadcaster config

- CONTRIBUTING.md
- LICENSE
- ur_bringup/CHANGELOG.rst
- ur_bringup/package.xml
- ur_controllers/CHANGELOG.rst
- ur_controllers/package.xml
- ur_dashboard_msgs/CHANGELOG.rst
- ur_dashboard_msgs/package.xml
- ur_description/CHANGELOG.rst
- ur_description/package.xml
- ur_moveit_config/CHANGELOG.rst
- ur_moveit_config/package.xml
- ur_robot_driver/CHANGELOG.rst
- ur_robot_driver/package.xml
I'll create the 2.0.0 tag directly on the target branch after this has been merged.
> Fox prepare release

- .github/mergify.yml
This should enable us to trigger backmerges by simply attaching a label to PRs on main.
> Add mergify rules for backporting

- README.md
> Remove vcstool instruction for galactic

- ur_bringup/package.xml
- ur_calibration/package.xml
- ur_controllers/package.xml
- ur_dashboard_msgs/package.xml
- ur_moveit_config/package.xml
- ur_robot_driver/package.xml
> Made sure all past maintainers are listed as authors

- ur_bringup/config/ur_controllers.yaml
- ur_robot_driver/config/ur_controllers.yaml
> Remove duplicated update_rate parameter

- .github/workflows/coverage-build.yml
> Update to CodeCov v3

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver-not-released.rolling.repos
This makes #441 obsolete and fixes #442
> Remove pinning ros2_control to specific branch

- ur_bringup/launch/ur_control.launch.py
> Don't attempt to start dashboard_client when use_fake_hardware is true

- .github/workflows/foxy-binary-build.yml
- .github/workflows/foxy-semi-binary-build.yml
- .github/workflows/galactic-binary-build.yml
- .github/workflows/galactic-execution-test.yml
- .github/workflows/galactic-semi-binary-build.yml
- .github/workflows/humble-binary-build.yml
- .github/workflows/humble-execution-test.yml
- .github/workflows/humble-semi-binary-build.yml
- .github/workflows/rolling-binary-build.yml
- .github/workflows/rolling-execution-test.yml
- .github/workflows/rolling-semi-binary-build.yml
- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
This should fix our pipelines for the current testing repo.
> Adapt jtc controller params to new param api

- ur_robot_driver/doc/setup_tool_communication.rst
> Add a note in the tool_comm doc about a URCap conflict

- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/resources/ros_control.urscript
Fixes #521
This basically adds https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/101
> Fix tool voltage setup

- README.md
- ur_robot_driver/doc/installation/robot_setup.rst
- ur_robot_driver/doc/usage.rst
Avoid duplication between README and package doc.
This also superseeds #446
Closes #493, #497
> Update and thin down README

- .github/workflows/ci-format.yml
ubuntu-latest seems to have switched to 22.04
> Make sure format job runs on 20.04

- ur_robot_driver/test/robot_driver.py
Previously, only the dashboard client was allowed to wait longer for the first service call, leading to flaky tests in cases where RTDE could not directly initialize. This can be seen in e.g. [this CI run](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/runs/4401593654/jobs/7707936503).
> Increase timeout for first test service call to driver

- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- ur_controllers/src/scaled_joint_trajectory_controller.cpp
- ur_robot_driver/test/robot_driver.py
I suggest merging #610 first, as we can then check this in CI
> Ros2 control api fix

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver-not-released.rolling.repos
- ur_bringup/launch/ur_control.launch.py
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/src/hardware_interface.cpp
This PR is part of splitting up into multiple parts https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/567
Note: The non-blocking read won't properly work like this without the PR in this series that allows starting the rtde communication at the latest point of time possible
> Adding additional parameters needed as step towards multiarm support (Multiarm part 1, recreation of #593)

- .github/dependabot.yml
- .github/workflows/update-ci.yml
This adds both dependabot and a pre-commit updater to our CI.
Closes #632
> Auto update ci

- ur_controllers/include/ur_controllers/gpio_controller.hpp
- ur_controllers/src/gpio_controller.cpp
- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
PR info:
- add hand back control service to enable return of urcap and mixed ROS/Teach Pendant programming
/closes #474
> Introduce hand back control service

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
> Calling on_deactivate in dtr

- ur_controllers/src/gpio_controller.cpp
> added missing command interfaces into gpio controller

- Universal_Robots_ROS2_Driver-not-released.humble.repos
- Universal_Robots_ROS2_Driver.humble.repos
> Use humble branch from Universal_Robots_ROS2_Description

- ur_moveit_config/launch/ur_moveit.launch.py
- ur_robot_driver/config/ur20_update_rate.yaml
- ur_robot_driver/doc/usage.rst
- ur_robot_driver/launch/ur20.launch.py
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/test/dashboard_client.py
- ur_robot_driver/test/robot_driver.py
- ur_robot_driver/test/urscript_interface.py
> Added support for UR20

- ur_robot_driver/doc/usage.rst
> Update link to MoveIt! documentation

- ur_robot_driver/launch/ur_control.launch.py
added the possibility to change the reverse_port, script_sender_port and trajectory_port to the main launch file.
> Port configuration 

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/package.xml
This should help debugging tremendously.
> Add backward_ros to driver

- Universal_Robots_ROS2_Driver.iron.repos
> Use iron branches for ros2_control

- .github/workflows/iron-binary-main.yml
- .github/workflows/iron-binary-testing.yml
- .github/workflows/iron-semi-binary-main.yml
- .github/workflows/iron-semi-binary-testing.yml
since ros2_control branched out, iron cannot be built on main necessarily.
> Do not build iron in rolling PRs

- README.md
Seem this useful info is missing.
We should maybe also state some top level requirements regarding ROS2 as well?
> Add a requirement section to the readme

- Universal_Robots_ROS2_Driver.iron.repos
Since ros2_control recently branched out for iron...
> Use ros2_control repos from iron branch for building iron

- ur_moveit_config/launch/ur_moveit.launch.py
- ur_robot_driver/launch/ur10.launch.py
- ur_robot_driver/launch/ur10e.launch.py
- ur_robot_driver/launch/ur16e.launch.py
- ur_robot_driver/launch/ur20.launch.py
- ur_robot_driver/launch/ur3.launch.py
- ur_robot_driver/launch/ur30.launch.py
- ur_robot_driver/launch/ur3e.launch.py
- ur_robot_driver/launch/ur5.launch.py
- ur_robot_driver/launch/ur5e.launch.py
- ur_robot_driver/launch/ur_control.launch.py
Related to:
https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/140
https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/pull/59
https://github.com/UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation/pull/16
> Fix multi-line strings in DeclareLaunchArgument

- .github/workflows/jazzy-binary-main.yml
- .github/workflows/jazzy-binary-testing.yml
- .github/workflows/jazzy-semi-binary-main.yml
- .github/workflows/jazzy-semi-binary-testing.yml
- README.md
- Universal_Robots_ROS2_Driver-not-released.jazzy.repos
- Universal_Robots_ROS2_Driver.jazzy.repos
- ci_status.md
* Add workflows for jazzy
* Add repos files for jazzy
* Add badges for jazzy to README and ci_status.md
* Move Rolling build badges to ubuntu noble
* Restructure README to move EOL distros out of the table
> Add Jazzy builds

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
- ur_robot_driver/src/hardware_interface.cpp
Backwards-compatible version of #1002
> Use robot_receive_timeout instead of keepalive_count

- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/test/test_common.py
This aims at fixing #1028, which is a regression introduced in #1020.
I first want the issue to show up in CI and then fix it with a consecutive commit.
> Fix launching without a tf_prefix specified

- ur_robot_driver/CMakeLists.txt
- ur_robot_driver/doc/usage.rst
- ur_robot_driver/scripts/example_move.py
- ur_robot_driver/test/example_move.py
This adds a note about installing `ros2controlcli` and an example move script.
> [doc] Add more documentation regarding usage

- README.md
This fixes #1061 
I'd like to update the picture of the robot family with this PR, as well, hence the draft status.
> Update README regarding payload including UR20 and UR30

- Universal_Robots_ROS2_Driver.iron.repos
ur_msgs was migrated to another branch.
> Update ur_msgs upstream branch

- ur/package.xml
- ur_calibration/package.xml
- ur_controllers/package.xml
- ur_dashboard_msgs/package.xml
- ur_moveit_config/package.xml
- ur_robot_driver/package.xml
This commit updates the package maintainers as the project's governance has changed a bit.
> Update package maintainers

- ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
Unearthed by https://github.com/ros-controls/ros2_control/pull/1972
> Remove unused visibility macros include

- ur_robot_driver/test/integration_test_controller_switch.py
The new black version enforces this change.
> Fix formatting

- ur_controllers/doc/index.rst
This pops up in the check_links workflow and seems about right.
> ur_controllers: doc -- Fix link to index page of driver

- ur_robot_driver/src/hardware_interface.cpp
The initializer list has been deprecated which raises a warning in the buildfarm.
> Use UrDriverConfig struct to initialize UrDriver

- ur_robot_driver/doc/features.rst
Add two features to the feature list. They have been implemented by now.
> Update feature list to what is implemented

- .github/workflows/kilted-binary-main.yml
- .github/workflows/kilted-binary-testing.yml
- .github/workflows/kilted-semi-binary-main.yml
- README.md
- Universal_Robots_ROS2_Driver.kilted.repos
- ci_status.md
This will be a draft until https://github.com/ros-industrial/industrial_ci/pull/906 is merged.
> Add CI for ROS Kilted Kaiju

- README.md
- ur_moveit_config/launch/ur_moveit.launch.py
- ur_robot_driver/config/ur15_update_rate.yaml
- ur_robot_driver/doc/usage/startup.rst
- ur_robot_driver/launch/ur15.launch.py
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/launch/ur_rsp.launch.py
- ur_robot_driver/test/test_common.py
- ur_robot_driver/urdf/ur.urdf.xacro
Adds support for directly starting a UR15
Draft until the description for Jazzy and Rolling is merged.
> Add support for UR15

- README.md
- ur_bringup/launch/ur15.launch.py
- ur_bringup/launch/ur20.launch.py
- ur_bringup/launch/ur30.launch.py
- ur_bringup/launch/ur_control.launch.py
- ur_moveit_config/launch/ur_moveit.launch.py
- ur_robot_driver/config/ur15_update_rate.yaml
- ur_robot_driver/doc/usage/startup.rst
- ur_robot_driver/launch/ur15.launch.py
- ur_robot_driver/launch/ur_control.launch.py
- ur_robot_driver/test/test_common.py
Keeping this draft until the description is merged.
> Add support for launching a UR15 robot

- .github/workflows/ci-format.yml
That workflow hasn't been updated in a while and doesn't work anymore. This PR should fix that.
> Update ci_format workflow components

- ur_controllers/src/scaled_joint_trajectory_controller.cpp
The upstream API [changed](https://github.com/ros-controls/ros2_controllers/pull/1720), so we have to follow.
> Use std_atomic<bool> in SJTC

- ur_robot_driver/launch/ur_rsp.launch.py
Probably leftover from copy-paste.
> Remove unneccessary arguments.

- Universal_Robots_ROS2_Driver.kilted.repos
- Universal_Robots_ROS2_Driver.rolling.repos
Since there are still outstanding upstream problems, let's try to fix them for our CI so we don't have to fly blind anymore.
> Fix semi-binary builds for Kilted & Rolling

- ur_robot_driver/doc/installation/real_time.rst
> Fix link to limits man page
